### ISSUE TITLE
[수정] 자가진단 결과 보여주는 recycler item 레이아웃 + 색상 변경

### ISSUE THREAD

**Issue by Ujaa** [Godeok/ChanNuLi#36]
**- item_self_diagnosis_result_container_v2.xml** 
![image](https://user-images.githubusercontent.com/40076944/126264919-84c18004-e12f-4e7d-9d53-f75bdc270f03.png)

이름 바꾸라는 거 x. 그냥 따로 만드느라 v2임. 코드 원래 파일로 복붙해도 됨.

**- 이 adapter 생성자에 this를 인자를 넣어주면 ok.**
색상 코드는 내가 가지고 있음.

**- resultRecycler/RecyclerAdapter .java**

    package kr.co.healthcare.self_diagnosis.ResultRecycler;
    
    import android.content.Context;
    import android.graphics.Color;
    import android.view.LayoutInflater;
    import android.view.View;
    import android.view.ViewGroup;
    import android.widget.TextView;
    import androidx.annotation.NonNull;
    import androidx.core.content.ContextCompat;
    import androidx.recyclerview.widget.RecyclerView;
    
    import kr.co.healthcare.R;
    import kr.co.healthcare.self_diagnosis.ResultDB.Result;
    
    import java.util.ArrayList;
    
    public class RecyclerAdapter extends RecyclerView.Adapter<RecyclerAdapter.MyViewHolder> {
    
        private Context context;
        private ArrayList<Result> resultData = new ArrayList<>();
        String[] disease_list = {"고혈압", "골관절염", "고지혈증", "요통/좌골신경통", "당뇨병", "골다공증", "치매"};
    
        RecyclerAdapter(Context context){
            this.context = context;
        }
        
        @NonNull
        @Override
        public MyViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
            View view = LayoutInflater.from(parent.getContext())
                    .inflate(R.layout.item_self_diagnosis_result_container,parent,false);
            return new MyViewHolder(view);
        }
    
        @Override
        public void onBindViewHolder(@NonNull MyViewHolder holder, int position) {
            holder.onBind(resultData.get(position), position);
        }
    
        @Override
        public int getItemCount() {
            return resultData.size();
        }
    
        public void addItem(Result result) {
            resultData.add(result);
        }
    
        public void addItems(ArrayList<Result> result) {
            resultData = result;
        }
    
        public class MyViewHolder extends RecyclerView.ViewHolder {
            private TextView tv_disease, tv_date, tv_count, tv_num;
    
            public MyViewHolder(@NonNull View itemView) {
                super(itemView);
    
                tv_disease = itemView.findViewById(R.id.tv_disease);
                tv_date = itemView.findViewById(R.id.tv_date);
                tv_count = itemView.findViewById(R.id.tv_count);
                tv_num = itemView.findViewById(R.id.tv_num);
            }
    
            public void onBind(final Result result, int position) {
                String s = "" + (position+1);
                tv_num.setText(""+s);
                tv_disease.setText(""+disease_list[result.getDisease()]);
                tv_date.setText(""+result.getDate());
    
                //검사 결과 텍스트뷰
                if(result.getCount()>5) {
                    tv_count.setBackgroundColor(ContextCompat.getColor(context, R.color.redColor));
                    tv_count.setText("위험");
                }
                else if(result.getCount()>3) {
                    tv_count.setBackgroundColor(ContextCompat.getColor(context, R.color.yellowColor));
                    tv_count.setText("주의");
                }
                else {
                    tv_count.setBackgroundColor(ContextCompat.getColor(context, R.color.primaryColor));
                    tv_count.setText("건강");
                }
            }
        }
    }

**Comment by Hong-Jinseo** [comment]
👌
