### ISSUE TITLE
마이페이지에 자가진단 결과 가져오기 위한 쿼리 추가

### ISSUE THREAD

**Issue by Hong-Jinseo** [Godeok/ChanNuLi#51]
@Ujaa 를 위한 자가진단 결과 DB 사용법     
=========

**1. DB 사용을 원하는 액티비티에 데이터베이스 import**
    
    import kr.co.healthcare.self_diagnosis.ResultDB.SelfDiagnosisResultDatabase;

**2. n번 질병의 평균 '예' 횟수를 int로 반환 (n은 0~6)**

    SelfDiagnosisResultDatabase.getInstance(this).resultDAO().getAverageCountOfDisease(n);  
  
  

#

**\* 사용 예시**

    textView.setText(AppDatabase.getInstance(this).resultDAO().getAverageCountOfDisease(1)+"개");  
 
**\* 평균 '예' 답변 횟수를 반환하는 것이기 때문에 '위험', '건강' 등으로 표현하고 싶으면 추가 가공 필요함**

    int count = AppDatabase.getInstance(this).resultDAO().getAverageCountOfDisease(1);
    if (count<5) textView.setText("건강합니다.");
    else textView.setText("위험합니다.");

**Comment by Ujaa** [comment]
친절한설명서 갬동했습니다

**Comment by Ujaa** [comment]
사용 후 제가 닫을게요
